import { MetadataRoute } from "next"

export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://medved-club.ru"
  return [
    { url: base, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: `${base}/tajskij-boks-schelkovo`, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: `${base}/muaj-taj-schelkovo`, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: `${base}/sboryi`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/sboryi/azovskoe-more`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/sboryi/tailand`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/dlya-devushek`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/dlya-detey`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/dlya-podrostkov`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/dlya-vzroslyh`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/dlya-novichkov`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/dlya-sportsmenov`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/dlya-roditelei`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/competitions`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${base}/tajskij-boks-fryazino`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-ivanteevka`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-monino`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-korolev`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-balashiha`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-pushkino`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-mytishchi`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-chernogolovka`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-losino-petrovskij`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-elektrostal`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-noginsk`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/blog`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.7 },
    { url: `${base}/blog/tayskiy-boks-dlya-detey`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/tayskiy-boks-s-nulya`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/tayskiy-boks-dlya-zhenshchin`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/tayskiy-boks-vs-boks`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/tayskiy-boks-dlya-podrostkov`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/tayskiy-boks-dlya-pohudeniya`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/sbory-po-tajskomu-boksu`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/kak-podgotovitsya-k-sorevnovaniyam`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/blog/chto-vzyat-na-trenirovku`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${base}/tajskij-boks-elektrogorsk`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-fryazevo`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/tajskij-boks-zheleznodorozhnyj`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${base}/edinoborstva-schelkovo`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/individualnye-trenirovki`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/split-trenirovki`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/personalnyj-trener-schelkovo`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/sportivnaya-sekciya-schelkovo`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/sekciya-dlya-detej-schelkovo`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/probnaya-trenirovka`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/raspisanie-i-tseny`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${base}/privacy`, lastModified: new Date(), changeFrequency: "yearly", priority: 0.3 },
  ]
}
